# The server name to use for the custom mxc:// URIs.
# This server name will effectively be a real Matrix server, it just won't implement anything other than media.
# You must either set up .well-known delegation from this domain to this program, or proxy the domain directly to this program.
server_name: giphy.example.com

# Optionally a custom .well-known response. This defaults to `server_name:443` if empty.
well_known_response:

# The proxy will use MSC3860/MSC3916 media download redirects if the requester supports it.
# Optionally, you can force redirects and not allow proxying at all by setting this to false.
allow_proxy: false

# Matrix server signing key to make the federation tester pass, same format as synapse's .signing.key file.
# You can generate one using `giphyproxy -generate-key`.
server_key: CHANGE ME

# Hostname where the proxy should listen on
hostname: 0.0.0.0
# Port where the proxy should listen on
port: 8008

# Redirect destination. This can be changed to serve a different format.
destination: https://i.giphy.com/%s.webp
tenor_destination: https://media.tenor.com/%s/image.webp

# API keys for Giphy and Tenor
giphy_api_key: YOUR_GIPHY_API_KEY
tenor_api_key: YOUR_TENOR_API_KEY

# Locale configuration (default: en_US)
# Used for Tenor and Giphy API requests
locale: en_US

# Optional path for serving GIFs (default: /gif/)
gif_path: /gif/

# Optional custom path for the index page (e.g. "/picker.html")
# If empty, will serve on root path (/)
index_path: /

# Path to directory containing local images to serve
storage_path: /storage